name = "CameraTrapTools"
uuid = "3263893d-0723-4c4b-8e8f-bb49e15bcdcd"
authors = ["Valentin Lucet"]
version = "0.1.0"

[deps]
ScanDir = "af3a3400-1793-11ea-1d1f-a522511abb08"

[compat]
ScanDir = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
